config:
  credentials: []
  project_repos:
    github.com/ARGOeu/argo-monitoring:
      branch: master
      repo: https://github.com/ARGOeu/argo-monitoring
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: fix/updatego
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/ARGOeu/argo-monitoring git:
        commands:
        - /usr/bin/env sh .sqa/script.flamingo_lively_skunk.sh
        container: qc.acc_pineapple_sweet_fox
  QC.Doc:
    repos:
      github.com/ARGOeu/argo-monitoring find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.fog_amused_gibbon.sh
        container: qc.doc_cherry_curious_kiwi
      github.com/ARGOeu/argo-monitoring git:
        commands:
        - /usr/bin/env sh .sqa/script.lilac_nurturing_gorilla.sh
        container: qc.doc_jet_proud_stork
      github.com/ARGOeu/argo-monitoring markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.heather_playful_gazelle.sh
        container: qc.doc_viridian_stoic_swan
  QC.Lic:
    repos:
      github.com/ARGOeu/argo-monitoring licensee:
        commands:
        - /usr/bin/env sh .sqa/script.powder_dramatic_manatee.sh
        container: qc.lic_fog_blissful_frog
  QC.Sty:
    repos:
      github.com/ARGOeu/argo-monitoring jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.cinnabar_harmonious_condor.sh
        container: qc.sty_horizon_zealous_sloth
  QC.Ver:
    repos:
      github.com/ARGOeu/argo-monitoring get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.gamboge_rugged_barracuda.sh
        container: qc.ver_orchid_playful_marmoset
timeout: 5400
