config:
  credentials: []
  project_repos:
    github.com/ARGOeu/argo-monitoring:
      branch: master
      repo: https://github.com/ARGOeu/argo-monitoring
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: fix/updatego
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/ARGOeu/argo-monitoring git:
        commands:
        - /usr/bin/env sh .sqa/script.azure_reflective_dolphin.sh
        container: qc.acc_marigold_spirited_panda
  QC.Doc:
    repos:
      github.com/ARGOeu/argo-monitoring find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.ash_exuberant_hydra.sh
        container: qc.doc_cornflower_worried_toad
      github.com/ARGOeu/argo-monitoring git:
        commands:
        - /usr/bin/env sh .sqa/script.sapphire_diplomatic_hyena.sh
        container: qc.doc_echelon_empathetic_vulture
      github.com/ARGOeu/argo-monitoring markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.denim_harmonious_quokka.sh
        container: qc.doc_malachite_independent_ostrich
  QC.Lic:
    repos:
      github.com/ARGOeu/argo-monitoring licensee:
        commands:
        - /usr/bin/env sh .sqa/script.onyx_protective_puffin.sh
        container: qc.lic_linen_tactful_jaguar
  QC.Sty:
    repos:
      github.com/ARGOeu/argo-monitoring jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.ceru_wondrous_manatee.sh
        container: qc.sty_fandango_outgoing_quoll
  QC.Ver:
    repos:
      github.com/ARGOeu/argo-monitoring get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.peach_worried_cougar.sh
        container: qc.ver_bronze_fair_hedgehog
timeout: 5400
